-- Create tah57.audit_logs table for tracking user actions
-- Run this script in your Oracle database

CREATE TABLE tah57.audit_logs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  action VARCHAR2(100) NOT NULL,
  resource_type VARCHAR2(100) NOT NULL,
  resource_id NUMBER,
  details VARCHAR2(100),
  ip_address VARCHAR2(45),
  user_agent VARCHAR2(500),
  status VARCHAR2(20) NOT NULL,
  error_message VARCHAR2(1000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for faster queries
CREATE INDEX idx_audit_logs_user_id ON tah57.audit_logs(user_id);
CREATE INDEX idx_audit_logs_resource_type ON tah57.audit_logs(resource_type);
CREATE INDEX idx_audit_logs_created_at ON tah57.audit_logs(created_at);
CREATE INDEX idx_audit_logs_action ON tah57.audit_logs(action);

-- Add comments for documentation
COMMENT ON TABLE tah57.audit_logs IS 'Tracks all user actions for security and compliance';
COMMENT ON COLUMN tah57.audit_logs.id IS 'Primary key, auto-generated';
COMMENT ON COLUMN tah57.audit_logs.user_id IS 'ID of the user who performed the action';
COMMENT ON COLUMN tah57.audit_logs.action IS 'Action type: create, update, delete, read, etc.';
COMMENT ON COLUMN tah57.audit_logs.resource_type IS 'Resource type: Patient, Doctor, Appointment, etc.';
COMMENT ON COLUMN tah57.audit_logs.resource_id IS 'ID of the affected resource';
COMMENT ON COLUMN tah57.audit_logs.details IS 'Additional details about the action';
COMMENT ON COLUMN tah57.audit_logs.ip_address IS 'IP address of the user';
COMMENT ON COLUMN tah57.audit_logs.user_agent IS 'User agent (browser) information';
COMMENT ON COLUMN tah57.audit_logs.status IS 'Status: success or failure';
COMMENT ON COLUMN tah57.audit_logs.error_message IS 'Error message if status is failure';
COMMENT ON COLUMN tah57.audit_logs.created_at IS 'Timestamp when the action occurred';

-- Grant permissions (adjust as needed)
-- GRANT SELECT, INSERT ON tah57.audit_logs TO your_app_user;

